import cmath
a=int(input('Enter a value :'))
b=int(input('Enter b value :'))
c=int(input('Enter c value :'))
d=(b**2)-(4*a*c)
print('Your equation is :',a,'x^2','+',b,'x','+',c,'=0')
print('The discriminant is :',d)
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)
print('The solution are {0} and {1}'.format(sol1,sol2))